# Generated by Django 4.1.5 on 2023-02-13 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f96f4f28-9690-45b0-ab8d-42add74f52b2'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
