# Generated by Django 4.1.5 on 2023-02-13 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_language_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21e03c7c-e11a-4942-bbe7-2af786a8f2bc'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
