# Generated by Django 4.1.5 on 2023-02-13 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_id_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03b6d29c-7aa7-4b77-bb5a-0dce9648f518'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
