# Generated by Django 4.1.5 on 2023-02-13 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc21dbb8-8575-41d9-af29-0793c8eecca8'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
