# Generated by Django 4.1.5 on 2023-02-17 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f82cf102-84a9-40ef-9ef6-e7614b020474'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
