# Generated by Django 4.1.5 on 2023-02-17 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4bf509a-2e54-4c67-aec0-e5aae6652c8a'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
