# Generated by Django 4.1.5 on 2023-02-17 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47a88d04-0d46-4d44-82cc-a6c5205ca200'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
