# Generated by Django 4.1.5 on 2023-02-17 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9b552ad-9847-4d27-935a-1a5819aff355'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
