# Generated by Django 4.1.5 on 2023-02-17 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b187c8d-68ae-4d95-9073-1d20e1b41045'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
