# Generated by Django 4.1.5 on 2023-02-17 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_bookinstance_borrower_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca395845-63c6-4ee2-84bf-fc1aac5b7018'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
