# Generated by Django 4.1.5 on 2023-02-17 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_bookinstance_options_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6dea142-afa3-49ce-881f-b0593804a1d7'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
