# Generated by Django 4.1.5 on 2023-02-20 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_author', 'Create new author'), ('can_delete_author', 'Delete Author'), ('can_update_author', 'Update Given Author'))},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ff92adeb-1faf-4b6b-8655-b1a27302d5a5'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
