# Generated by Django 4.1.5 on 2023-02-23 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_author_date_of_death_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e29a6639-8b79-4988-a519-8a12b8febc57'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
