# Generated by Django 4.1.5 on 2023-02-23 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c475a602-647d-40ef-af8d-cad2b6947b90'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
